apiVersion: apps/v1
kind: Deployment
metadata:
  name: cityinfo-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cityinfo
  template:
    metadata:
      labels:
        app: cityinfo
    spec:
      containers:
      - name: cityinfo
        image: nirmaldocker1987/cityinfoapp:${BUILD_NUMBER}
        ports:
        - containerPort: 5000
        envFrom:
         - secretRef:
             name: cityinfo-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cityinfo-service
spec:
  selector:
    app: cityinfo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  sessionAffinity: None
  type: LoadBalancer
